### ISSUE TITLE
Question about extents

### ISSUE THREAD

**Issue by jensendarren** [propublica/simpler-tiles#8]
I am using Simpler Tiles to render maps with point data and I want to set the zoom extents of the map when the page loads based on the extents of the dataset. Is there a way I can query the shape file using Simpler Tiles API to get the extents of the data and use that to set the map extents?

BTW: I know how to get 'Extent' info using ogrinfo tool: ogrinfo -sql "select * from 'my_layer'" myfile.shp

Its the "Extent" value from this output that I'd love to pull using the Simpler Tiles library!

Many thanks for your help!

**Comment by thejefflarson** [comment]
Not in simpler-tiles itself, no, but I'd use something more tailor made
for geometric operations like rgeo:

https://github.com/rgeo/rgeo

Glad the library is useful for you!
